### ISSUE TITLE
Correct way to implement using GTM?

### ISSUE THREAD

**Issue by lupocreative** [robflaherty/jquery-scrolldepth#107] opened 2017-03-20 17:56 UTC
Hi,

I can see that this project has seen check-ins/updates/fixes within the last 3 months, which is really good to see.  But on the project page (http://scrolldepth.parsnip.io/) is a link to this blog post, re: implementing via Google Tag Manager:
http://andygibson.us/2013/10/track-scroll-depth-using-google-tag-manager/

This information doesn't seem to have been updated for three years. Is it still the correct way to implement via GTM?

Thanks,
Simon

**Comment by nauta** [comment] 2017-03-23 07:45
There's a more up-to-date blog post here: 
http://www.amazeemetrics.com/en/blog/google-tag-manager-tutorial-scroll-tracking-5-steps
which does a good job describing a GTM implementation. 
Just remember to use the Github version of jquery.scrolldepth.js - the script the blog post links to is outdated.

**Comment by lupocreative** [comment] 2017-03-24 21:16
Thank you!

**Comment by lanedenson** [comment] 2017-05-04 17:11
I was able to get the amazemetrics.com steps working properly, but only by using v0.4.1 of scrolldistance.js.  If I tried v0.9 or v1.0, the scroll tracking event never fires.

**Comment by RottenJoe** [comment] 2017-05-05 07:09
Hi @lanedenson 

Add the following code at the end of the script before the closing script tag:
`jQuery(function() {
  jQuery.scrollDepth();
});`

The problem is, that the v0.4.1 already calls the function while the newer versions do not.

Cheers

**Comment by lupocreative** [comment] 2017-05-08 19:18
Thank you, @RottenJoe - you just saved us from additional hours of tearing hair out!

**Comment by tatianafrank** [comment] 2017-10-19 18:20
Im using the library without GTM and it's not firing even after implementing above suggestion from @RottenJoe

**Comment by Jeffco3** [comment] 2017-10-19 18:39
@tatianafrank GTM now has a built-in variable for scroll tracking. Def do it that way instead.

**Comment by tatianafrank** [comment] 2017-10-19 18:41
Amazing thank you for the heads up @Jeffco3 !!

**Closed** 2020-06-26 14:52 UTC
